--
-- PostgreSQL database dump
--

\restrict SnKIxmebAg9eAcZw3jy0yRlAggSpV91AjE1oiH5k9kxJDr5cw1Dnr9gmQwa765q

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: leaderboard; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leaderboard (
    id bigint NOT NULL,
    fastest_launch_time bigint NOT NULL,
    max_depth_mined integer NOT NULL,
    player_id bigint
);


ALTER TABLE public.leaderboard OWNER TO postgres;

--
-- Name: leaderboard_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leaderboard ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leaderboard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.player (
    id bigint NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.player OWNER TO postgres;

--
-- Name: player_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: save_state; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.save_state (
    id bigint NOT NULL,
    credits integer NOT NULL,
    current_planet character varying(255),
    data text,
    updated_at timestamp(6) with time zone,
    player_id bigint
);


ALTER TABLE public.save_state OWNER TO postgres;

--
-- Name: save_state_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.save_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.save_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: leaderboard; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.leaderboard (id, fastest_launch_time, max_depth_mined, player_id) FROM stdin;
1	0	56077	1
\.


--
-- Data for Name: player; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.player (id, password_hash, username) FROM stdin;
1	$2a$10$lvC/8rvP/158KOF2KwkM1.zlbnazlgrTeq6l/vWTnUnqHzQMmLVWW	admin
\.


--
-- Data for Name: save_state; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.save_state (id, credits, current_planet, data, updated_at, player_id) FROM stdin;
1	0	PROXIMA_B	{"hub": {"x": 47.5, "y": 1.0, "tier": 1, "width": 6.0, "height": 3.0}, "world": {"seed": 1779422826100, "machines": [], "minedCells": [[55, 0], [56, 0], [54, 1], [55, 1], [56, 1], [57, 1], [57, 295], [56, 296], [58, 296], [55, 298], [57, 298], [58, 298], [59, 298], [53, 299]], "placedBlocks": [{"col": 54, "row": -2, "type": "STONE"}, {"col": 56, "row": -3, "type": "STONE"}, {"col": 58, "row": -3, "type": "STONE"}, {"col": 59, "row": -3, "type": "STONE"}, {"col": 60, "row": -3, "type": "STONE"}, {"col": 59, "row": -5, "type": "STONE"}, {"col": 58, "row": -6, "type": "STONE"}, {"col": 57, "row": -5, "type": "STONE"}]}, "player": {"x": 51.89249, "y": 1.0, "inventory": {"DIRT": 5}, "wheelTier": 1, "activeSlot": 1, "maxBattery": 120.0, "batteryTier": 1, "jetpackTier": 1, "drillStrength": 1, "currentBattery": 120.0, "machineInventory": {}}, "globalVault": {"DIRT": 999999, "STONE": 999999, "RAW_COAL": 999999, "RAW_GOLD": 999999, "RAW_IRON": 999999, "REFINERY": 999999, "IRON_GEAR": 999999, "AUTO_MINER": 999999, "FUEL_MIXER": 999999, "GOLD_INGOT": 999999, "HULL_PRESS": 999999, "IRON_INGOT": 999999, "RAW_COPPER": 999999, "CIRCUIT_FAB": 999999, "COPPER_WIRE": 999999, "RAW_SILICON": 999999, "RAW_URANIUM": 999999, "ROCKET_FUEL": 999999, "COPPER_INGOT": 999999, "GOLD_SMELTER": 999999, "HULL_PLATING": 999999, "IRON_SMELTER": 999999, "RAW_OBSIDIAN": 999999, "CIRCUIT_BOARD": 999999, "SILICON_WAFER": 999999, "COAL_GENERATOR": 999999, "COPPER_SMELTER": 999999, "GEAR_ASSEMBLER": 999999, "WIRE_ASSEMBLER": 999999}, "schemaVersion": 1}	2026-05-22 11:10:28.443602+07	1
\.


--
-- Name: leaderboard_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.leaderboard_id_seq', 1, true);


--
-- Name: player_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.player_id_seq', 1, true);


--
-- Name: save_state_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.save_state_id_seq', 1, true);


--
-- Name: leaderboard leaderboard_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leaderboard
    ADD CONSTRAINT leaderboard_pkey PRIMARY KEY (id);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);


--
-- Name: save_state save_state_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.save_state
    ADD CONSTRAINT save_state_pkey PRIMARY KEY (id);


--
-- Name: player uko39xn8lmj05iew7d2tgw836jy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT uko39xn8lmj05iew7d2tgw836jy UNIQUE (username);


--
-- Name: leaderboard uksgx6ocnqth2gxrjo877nexchj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leaderboard
    ADD CONSTRAINT uksgx6ocnqth2gxrjo877nexchj UNIQUE (player_id);


--
-- Name: save_state fk8bsmfkcoqtbr4sit6hi0gjj5m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.save_state
    ADD CONSTRAINT fk8bsmfkcoqtbr4sit6hi0gjj5m FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- Name: leaderboard fka3o0g7hk6o3t8h6xmo5sqgtik; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leaderboard
    ADD CONSTRAINT fka3o0g7hk6o3t8h6xmo5sqgtik FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- PostgreSQL database dump complete
--

\unrestrict SnKIxmebAg9eAcZw3jy0yRlAggSpV91AjE1oiH5k9kxJDr5cw1Dnr9gmQwa765q

